// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewCreateMfaPolicyParams creates a new CreateMfaPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMfaPolicyParams() *CreateMfaPolicyParams {
	return &CreateMfaPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMfaPolicyParamsWithTimeout creates a new CreateMfaPolicyParams object
// with the ability to set a timeout on a request.
func NewCreateMfaPolicyParamsWithTimeout(timeout time.Duration) *CreateMfaPolicyParams {
	return &CreateMfaPolicyParams{
		timeout: timeout,
	}
}

// NewCreateMfaPolicyParamsWithContext creates a new CreateMfaPolicyParams object
// with the ability to set a context for a request.
func NewCreateMfaPolicyParamsWithContext(ctx context.Context) *CreateMfaPolicyParams {
	return &CreateMfaPolicyParams{
		Context: ctx,
	}
}

// NewCreateMfaPolicyParamsWithHTTPClient creates a new CreateMfaPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMfaPolicyParamsWithHTTPClient(client *http.Client) *CreateMfaPolicyParams {
	return &CreateMfaPolicyParams{
		HTTPClient: client,
	}
}

/*
CreateMfaPolicyParams contains all the parameters to send to the API endpoint

	for the create mfa policy operation.

	Typically these are written to a http.Request.
*/
type CreateMfaPolicyParams struct {

	// Body.
	Body *models.CreateMfaPolicyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create mfa policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMfaPolicyParams) WithDefaults() *CreateMfaPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create mfa policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMfaPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create mfa policy params
func (o *CreateMfaPolicyParams) WithTimeout(timeout time.Duration) *CreateMfaPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create mfa policy params
func (o *CreateMfaPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create mfa policy params
func (o *CreateMfaPolicyParams) WithContext(ctx context.Context) *CreateMfaPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create mfa policy params
func (o *CreateMfaPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create mfa policy params
func (o *CreateMfaPolicyParams) WithHTTPClient(client *http.Client) *CreateMfaPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create mfa policy params
func (o *CreateMfaPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create mfa policy params
func (o *CreateMfaPolicyParams) WithBody(body *models.CreateMfaPolicyRequest) *CreateMfaPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create mfa policy params
func (o *CreateMfaPolicyParams) SetBody(body *models.CreateMfaPolicyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMfaPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
