// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// CreateMfaPolicyReader is a Reader for the CreateMfaPolicy structure.
type CreateMfaPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMfaPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateMfaPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/submit/create_mfa_policy] CreateMfaPolicy", response, response.Code())
	}
}

// NewCreateMfaPolicyOK creates a CreateMfaPolicyOK with default headers values
func NewCreateMfaPolicyOK() *CreateMfaPolicyOK {
	return &CreateMfaPolicyOK{}
}

/*
CreateMfaPolicyOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateMfaPolicyOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this create mfa policy o k response has a 2xx status code
func (o *CreateMfaPolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create mfa policy o k response has a 3xx status code
func (o *CreateMfaPolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create mfa policy o k response has a 4xx status code
func (o *CreateMfaPolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create mfa policy o k response has a 5xx status code
func (o *CreateMfaPolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create mfa policy o k response a status code equal to that given
func (o *CreateMfaPolicyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create mfa policy o k response
func (o *CreateMfaPolicyOK) Code() int {
	return 200
}

func (o *CreateMfaPolicyOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_mfa_policy][%d] createMfaPolicyOK  %+v", 200, o.Payload)
}

func (o *CreateMfaPolicyOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_mfa_policy][%d] createMfaPolicyOK  %+v", 200, o.Payload)
}

func (o *CreateMfaPolicyOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *CreateMfaPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
