// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// DeleteMfaPolicyReader is a Reader for the DeleteMfaPolicy structure.
type DeleteMfaPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMfaPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMfaPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/submit/delete_mfa_policy] DeleteMfaPolicy", response, response.Code())
	}
}

// NewDeleteMfaPolicyOK creates a DeleteMfaPolicyOK with default headers values
func NewDeleteMfaPolicyOK() *DeleteMfaPolicyOK {
	return &DeleteMfaPolicyOK{}
}

/*
DeleteMfaPolicyOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteMfaPolicyOK struct {
	Payload *models.ActivityResponse
}

// IsSuccess returns true when this delete mfa policy o k response has a 2xx status code
func (o *DeleteMfaPolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete mfa policy o k response has a 3xx status code
func (o *DeleteMfaPolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete mfa policy o k response has a 4xx status code
func (o *DeleteMfaPolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete mfa policy o k response has a 5xx status code
func (o *DeleteMfaPolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete mfa policy o k response a status code equal to that given
func (o *DeleteMfaPolicyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete mfa policy o k response
func (o *DeleteMfaPolicyOK) Code() int {
	return 200
}

func (o *DeleteMfaPolicyOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_mfa_policy][%d] deleteMfaPolicyOK  %+v", 200, o.Payload)
}

func (o *DeleteMfaPolicyOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_mfa_policy][%d] deleteMfaPolicyOK  %+v", 200, o.Payload)
}

func (o *DeleteMfaPolicyOK) GetPayload() *models.ActivityResponse {
	return o.Payload
}

func (o *DeleteMfaPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
