// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewDeleteMfaPolicyParams creates a new DeleteMfaPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteMfaPolicyParams() *DeleteMfaPolicyParams {
	return &DeleteMfaPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMfaPolicyParamsWithTimeout creates a new DeleteMfaPolicyParams object
// with the ability to set a timeout on a request.
func NewDeleteMfaPolicyParamsWithTimeout(timeout time.Duration) *DeleteMfaPolicyParams {
	return &DeleteMfaPolicyParams{
		timeout: timeout,
	}
}

// NewDeleteMfaPolicyParamsWithContext creates a new DeleteMfaPolicyParams object
// with the ability to set a context for a request.
func NewDeleteMfaPolicyParamsWithContext(ctx context.Context) *DeleteMfaPolicyParams {
	return &DeleteMfaPolicyParams{
		Context: ctx,
	}
}

// NewDeleteMfaPolicyParamsWithHTTPClient creates a new DeleteMfaPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteMfaPolicyParamsWithHTTPClient(client *http.Client) *DeleteMfaPolicyParams {
	return &DeleteMfaPolicyParams{
		HTTPClient: client,
	}
}

/*
DeleteMfaPolicyParams contains all the parameters to send to the API endpoint

	for the delete mfa policy operation.

	Typically these are written to a http.Request.
*/
type DeleteMfaPolicyParams struct {

	// Body.
	Body *models.DeleteMfaPolicyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete mfa policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMfaPolicyParams) WithDefaults() *DeleteMfaPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete mfa policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMfaPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete mfa policy params
func (o *DeleteMfaPolicyParams) WithTimeout(timeout time.Duration) *DeleteMfaPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete mfa policy params
func (o *DeleteMfaPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete mfa policy params
func (o *DeleteMfaPolicyParams) WithContext(ctx context.Context) *DeleteMfaPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete mfa policy params
func (o *DeleteMfaPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete mfa policy params
func (o *DeleteMfaPolicyParams) WithHTTPClient(client *http.Client) *DeleteMfaPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete mfa policy params
func (o *DeleteMfaPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete mfa policy params
func (o *DeleteMfaPolicyParams) WithBody(body *models.DeleteMfaPolicyRequest) *DeleteMfaPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete mfa policy params
func (o *DeleteMfaPolicyParams) SetBody(body *models.DeleteMfaPolicyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMfaPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
