// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewGetMfaStatusParams creates a new GetMfaStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMfaStatusParams() *GetMfaStatusParams {
	return &GetMfaStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMfaStatusParamsWithTimeout creates a new GetMfaStatusParams object
// with the ability to set a timeout on a request.
func NewGetMfaStatusParamsWithTimeout(timeout time.Duration) *GetMfaStatusParams {
	return &GetMfaStatusParams{
		timeout: timeout,
	}
}

// NewGetMfaStatusParamsWithContext creates a new GetMfaStatusParams object
// with the ability to set a context for a request.
func NewGetMfaStatusParamsWithContext(ctx context.Context) *GetMfaStatusParams {
	return &GetMfaStatusParams{
		Context: ctx,
	}
}

// NewGetMfaStatusParamsWithHTTPClient creates a new GetMfaStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMfaStatusParamsWithHTTPClient(client *http.Client) *GetMfaStatusParams {
	return &GetMfaStatusParams{
		HTTPClient: client,
	}
}

/*
GetMfaStatusParams contains all the parameters to send to the API endpoint

	for the get mfa status operation.

	Typically these are written to a http.Request.
*/
type GetMfaStatusParams struct {

	// Body.
	Body *models.GetMfaStatusRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get mfa status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMfaStatusParams) WithDefaults() *GetMfaStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get mfa status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMfaStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get mfa status params
func (o *GetMfaStatusParams) WithTimeout(timeout time.Duration) *GetMfaStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mfa status params
func (o *GetMfaStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mfa status params
func (o *GetMfaStatusParams) WithContext(ctx context.Context) *GetMfaStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mfa status params
func (o *GetMfaStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mfa status params
func (o *GetMfaStatusParams) WithHTTPClient(client *http.Client) *GetMfaStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mfa status params
func (o *GetMfaStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get mfa status params
func (o *GetMfaStatusParams) WithBody(body *models.GetMfaStatusRequest) *GetMfaStatusParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get mfa status params
func (o *GetMfaStatusParams) SetBody(body *models.GetMfaStatusRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetMfaStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
