// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// GetMfaStatusReader is a Reader for the GetMfaStatus structure.
type GetMfaStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMfaStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMfaStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/query/get_mfa_status] GetMfaStatus", response, response.Code())
	}
}

// NewGetMfaStatusOK creates a GetMfaStatusOK with default headers values
func NewGetMfaStatusOK() *GetMfaStatusOK {
	return &GetMfaStatusOK{}
}

/*
GetMfaStatusOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetMfaStatusOK struct {
	Payload *models.GetMfaStatusResponse
}

// IsSuccess returns true when this get mfa status o k response has a 2xx status code
func (o *GetMfaStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get mfa status o k response has a 3xx status code
func (o *GetMfaStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get mfa status o k response has a 4xx status code
func (o *GetMfaStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get mfa status o k response has a 5xx status code
func (o *GetMfaStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get mfa status o k response a status code equal to that given
func (o *GetMfaStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get mfa status o k response
func (o *GetMfaStatusOK) Code() int {
	return 200
}

func (o *GetMfaStatusOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_mfa_status][%d] getMfaStatusOK  %+v", 200, o.Payload)
}

func (o *GetMfaStatusOK) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_mfa_status][%d] getMfaStatusOK  %+v", 200, o.Payload)
}

func (o *GetMfaStatusOK) GetPayload() *models.GetMfaStatusResponse {
	return o.Payload
}

func (o *GetMfaStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetMfaStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
