// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewGetMfaPoliciesParams creates a new GetMfaPoliciesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMfaPoliciesParams() *GetMfaPoliciesParams {
	return &GetMfaPoliciesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMfaPoliciesParamsWithTimeout creates a new GetMfaPoliciesParams object
// with the ability to set a timeout on a request.
func NewGetMfaPoliciesParamsWithTimeout(timeout time.Duration) *GetMfaPoliciesParams {
	return &GetMfaPoliciesParams{
		timeout: timeout,
	}
}

// NewGetMfaPoliciesParamsWithContext creates a new GetMfaPoliciesParams object
// with the ability to set a context for a request.
func NewGetMfaPoliciesParamsWithContext(ctx context.Context) *GetMfaPoliciesParams {
	return &GetMfaPoliciesParams{
		Context: ctx,
	}
}

// NewGetMfaPoliciesParamsWithHTTPClient creates a new GetMfaPoliciesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMfaPoliciesParamsWithHTTPClient(client *http.Client) *GetMfaPoliciesParams {
	return &GetMfaPoliciesParams{
		HTTPClient: client,
	}
}

/*
GetMfaPoliciesParams contains all the parameters to send to the API endpoint

	for the get mfa policies operation.

	Typically these are written to a http.Request.
*/
type GetMfaPoliciesParams struct {

	// Body.
	Body *models.GetMfaPoliciesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get mfa policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMfaPoliciesParams) WithDefaults() *GetMfaPoliciesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get mfa policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMfaPoliciesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get mfa policies params
func (o *GetMfaPoliciesParams) WithTimeout(timeout time.Duration) *GetMfaPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mfa policies params
func (o *GetMfaPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mfa policies params
func (o *GetMfaPoliciesParams) WithContext(ctx context.Context) *GetMfaPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mfa policies params
func (o *GetMfaPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mfa policies params
func (o *GetMfaPoliciesParams) WithHTTPClient(client *http.Client) *GetMfaPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mfa policies params
func (o *GetMfaPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get mfa policies params
func (o *GetMfaPoliciesParams) WithBody(body *models.GetMfaPoliciesRequest) *GetMfaPoliciesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get mfa policies params
func (o *GetMfaPoliciesParams) SetBody(body *models.GetMfaPoliciesRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetMfaPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
