// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// GetMfaPolicyReader is a Reader for the GetMfaPolicy structure.
type GetMfaPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMfaPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMfaPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/query/get_mfa_policy] GetMfaPolicy", response, response.Code())
	}
}

// NewGetMfaPolicyOK creates a GetMfaPolicyOK with default headers values
func NewGetMfaPolicyOK() *GetMfaPolicyOK {
	return &GetMfaPolicyOK{}
}

/*
GetMfaPolicyOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetMfaPolicyOK struct {
	Payload *models.GetMfaPolicyResponse
}

// IsSuccess returns true when this get mfa policy o k response has a 2xx status code
func (o *GetMfaPolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get mfa policy o k response has a 3xx status code
func (o *GetMfaPolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get mfa policy o k response has a 4xx status code
func (o *GetMfaPolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get mfa policy o k response has a 5xx status code
func (o *GetMfaPolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get mfa policy o k response a status code equal to that given
func (o *GetMfaPolicyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get mfa policy o k response
func (o *GetMfaPolicyOK) Code() int {
	return 200
}

func (o *GetMfaPolicyOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_mfa_policy][%d] getMfaPolicyOK  %+v", 200, o.Payload)
}

func (o *GetMfaPolicyOK) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_mfa_policy][%d] getMfaPolicyOK  %+v", 200, o.Payload)
}

func (o *GetMfaPolicyOK) GetPayload() *models.GetMfaPolicyResponse {
	return o.Payload
}

func (o *GetMfaPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetMfaPolicyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
