// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewGetMfaPolicyParams creates a new GetMfaPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMfaPolicyParams() *GetMfaPolicyParams {
	return &GetMfaPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMfaPolicyParamsWithTimeout creates a new GetMfaPolicyParams object
// with the ability to set a timeout on a request.
func NewGetMfaPolicyParamsWithTimeout(timeout time.Duration) *GetMfaPolicyParams {
	return &GetMfaPolicyParams{
		timeout: timeout,
	}
}

// NewGetMfaPolicyParamsWithContext creates a new GetMfaPolicyParams object
// with the ability to set a context for a request.
func NewGetMfaPolicyParamsWithContext(ctx context.Context) *GetMfaPolicyParams {
	return &GetMfaPolicyParams{
		Context: ctx,
	}
}

// NewGetMfaPolicyParamsWithHTTPClient creates a new GetMfaPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMfaPolicyParamsWithHTTPClient(client *http.Client) *GetMfaPolicyParams {
	return &GetMfaPolicyParams{
		HTTPClient: client,
	}
}

/*
GetMfaPolicyParams contains all the parameters to send to the API endpoint

	for the get mfa policy operation.

	Typically these are written to a http.Request.
*/
type GetMfaPolicyParams struct {

	// Body.
	Body *models.GetMfaPolicyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get mfa policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMfaPolicyParams) WithDefaults() *GetMfaPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get mfa policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMfaPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get mfa policy params
func (o *GetMfaPolicyParams) WithTimeout(timeout time.Duration) *GetMfaPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mfa policy params
func (o *GetMfaPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mfa policy params
func (o *GetMfaPolicyParams) WithContext(ctx context.Context) *GetMfaPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mfa policy params
func (o *GetMfaPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mfa policy params
func (o *GetMfaPolicyParams) WithHTTPClient(client *http.Client) *GetMfaPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mfa policy params
func (o *GetMfaPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get mfa policy params
func (o *GetMfaPolicyParams) WithBody(body *models.GetMfaPolicyRequest) *GetMfaPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get mfa policy params
func (o *GetMfaPolicyParams) SetBody(body *models.GetMfaPolicyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetMfaPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
