// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// GetMfaPoliciesReader is a Reader for the GetMfaPolicies structure.
type GetMfaPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMfaPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMfaPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/query/get_mfa_policies] GetMfaPolicies", response, response.Code())
	}
}

// NewGetMfaPoliciesOK creates a GetMfaPoliciesOK with default headers values
func NewGetMfaPoliciesOK() *GetMfaPoliciesOK {
	return &GetMfaPoliciesOK{}
}

/*
GetMfaPoliciesOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetMfaPoliciesOK struct {
	Payload *models.GetMfaPoliciesResponse
}

// IsSuccess returns true when this get mfa policies o k response has a 2xx status code
func (o *GetMfaPoliciesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get mfa policies o k response has a 3xx status code
func (o *GetMfaPoliciesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get mfa policies o k response has a 4xx status code
func (o *GetMfaPoliciesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get mfa policies o k response has a 5xx status code
func (o *GetMfaPoliciesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get mfa policies o k response a status code equal to that given
func (o *GetMfaPoliciesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get mfa policies o k response
func (o *GetMfaPoliciesOK) Code() int {
	return 200
}

func (o *GetMfaPoliciesOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_mfa_policies][%d] getMfaPoliciesOK  %+v", 200, o.Payload)
}

func (o *GetMfaPoliciesOK) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_mfa_policies][%d] getMfaPoliciesOK  %+v", 200, o.Payload)
}

func (o *GetMfaPoliciesOK) GetPayload() *models.GetMfaPoliciesResponse {
	return o.Payload
}

func (o *GetMfaPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetMfaPoliciesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
