// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new m f a policies API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for m f a policies API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateMfaPolicy(params *CreateMfaPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMfaPolicyOK, error)

	DeleteMfaPolicy(params *DeleteMfaPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMfaPolicyOK, error)

	GetMfaPolicies(params *GetMfaPoliciesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMfaPoliciesOK, error)

	GetMfaPolicy(params *GetMfaPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMfaPolicyOK, error)

	GetMfaStatus(params *GetMfaStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMfaStatusOK, error)

	UpdateMfaPolicy(params *UpdateMfaPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateMfaPolicyOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateMfaPolicy creates m f a policy

Create a new MFA policy for a user.
*/
func (a *Client) CreateMfaPolicy(params *CreateMfaPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMfaPolicyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateMfaPolicyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateMfaPolicy",
		Method:             "POST",
		PathPattern:        "/public/v1/submit/create_mfa_policy",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateMfaPolicyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateMfaPolicyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateMfaPolicy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteMfaPolicy deletes m f a policy

Delete an MFA policy for a user.
*/
func (a *Client) DeleteMfaPolicy(params *DeleteMfaPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMfaPolicyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteMfaPolicyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteMfaPolicy",
		Method:             "POST",
		PathPattern:        "/public/v1/submit/delete_mfa_policy",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteMfaPolicyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteMfaPolicyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteMfaPolicy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetMfaPolicies gets m f a policies

Get all MFA policies for a user.
*/
func (a *Client) GetMfaPolicies(params *GetMfaPoliciesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMfaPoliciesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMfaPoliciesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetMfaPolicies",
		Method:             "POST",
		PathPattern:        "/public/v1/query/get_mfa_policies",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetMfaPoliciesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMfaPoliciesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetMfaPolicies: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetMfaPolicy gets m f a policy

Get a single MFA policy for a user.
*/
func (a *Client) GetMfaPolicy(params *GetMfaPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMfaPolicyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMfaPolicyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetMfaPolicy",
		Method:             "POST",
		PathPattern:        "/public/v1/query/get_mfa_policy",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetMfaPolicyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMfaPolicyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetMfaPolicy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetMfaStatus gets m f a status

Get the MFA status of an activity for one user or all voting users.
*/
func (a *Client) GetMfaStatus(params *GetMfaStatusParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMfaStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMfaStatusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetMfaStatus",
		Method:             "POST",
		PathPattern:        "/public/v1/query/get_mfa_status",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetMfaStatusReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMfaStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetMfaStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateMfaPolicy updates m f a policy

Update an MFA policy for a user.
*/
func (a *Client) UpdateMfaPolicy(params *UpdateMfaPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateMfaPolicyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateMfaPolicyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateMfaPolicy",
		Method:             "POST",
		PathPattern:        "/public/v1/submit/update_mfa_policy",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateMfaPolicyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateMfaPolicyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for UpdateMfaPolicy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
