// Code generated by go-swagger; DO NOT EDIT.

package m_f_a_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewUpdateMfaPolicyParams creates a new UpdateMfaPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateMfaPolicyParams() *UpdateMfaPolicyParams {
	return &UpdateMfaPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMfaPolicyParamsWithTimeout creates a new UpdateMfaPolicyParams object
// with the ability to set a timeout on a request.
func NewUpdateMfaPolicyParamsWithTimeout(timeout time.Duration) *UpdateMfaPolicyParams {
	return &UpdateMfaPolicyParams{
		timeout: timeout,
	}
}

// NewUpdateMfaPolicyParamsWithContext creates a new UpdateMfaPolicyParams object
// with the ability to set a context for a request.
func NewUpdateMfaPolicyParamsWithContext(ctx context.Context) *UpdateMfaPolicyParams {
	return &UpdateMfaPolicyParams{
		Context: ctx,
	}
}

// NewUpdateMfaPolicyParamsWithHTTPClient creates a new UpdateMfaPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateMfaPolicyParamsWithHTTPClient(client *http.Client) *UpdateMfaPolicyParams {
	return &UpdateMfaPolicyParams{
		HTTPClient: client,
	}
}

/*
UpdateMfaPolicyParams contains all the parameters to send to the API endpoint

	for the update mfa policy operation.

	Typically these are written to a http.Request.
*/
type UpdateMfaPolicyParams struct {

	// Body.
	Body *models.UpdateMfaPolicyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update mfa policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateMfaPolicyParams) WithDefaults() *UpdateMfaPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update mfa policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateMfaPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update mfa policy params
func (o *UpdateMfaPolicyParams) WithTimeout(timeout time.Duration) *UpdateMfaPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update mfa policy params
func (o *UpdateMfaPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update mfa policy params
func (o *UpdateMfaPolicyParams) WithContext(ctx context.Context) *UpdateMfaPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update mfa policy params
func (o *UpdateMfaPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update mfa policy params
func (o *UpdateMfaPolicyParams) WithHTTPClient(client *http.Client) *UpdateMfaPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update mfa policy params
func (o *UpdateMfaPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update mfa policy params
func (o *UpdateMfaPolicyParams) WithBody(body *models.UpdateMfaPolicyRequest) *UpdateMfaPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update mfa policy params
func (o *UpdateMfaPolicyParams) SetBody(body *models.UpdateMfaPolicyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMfaPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
