// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/client/activities"
	"github.com/0xkey-io/sdk-go/pkg/api/client/api_keys"
	"github.com/0xkey-io/sdk-go/pkg/api/client/app_proof"
	"github.com/0xkey-io/sdk-go/pkg/api/client/authenticators"
	"github.com/0xkey-io/sdk-go/pkg/api/client/boot_proof"
	"github.com/0xkey-io/sdk-go/pkg/api/client/broadcasting"
	"github.com/0xkey-io/sdk-go/pkg/api/client/consensus"
	"github.com/0xkey-io/sdk-go/pkg/api/client/features"
	"github.com/0xkey-io/sdk-go/pkg/api/client/invitations"
	"github.com/0xkey-io/sdk-go/pkg/api/client/on_ramp"
	"github.com/0xkey-io/sdk-go/pkg/api/client/operations"
	"github.com/0xkey-io/sdk-go/pkg/api/client/organizations"
	"github.com/0xkey-io/sdk-go/pkg/api/client/policies"
	"github.com/0xkey-io/sdk-go/pkg/api/client/private_key_tags"
	"github.com/0xkey-io/sdk-go/pkg/api/client/private_keys"
	"github.com/0xkey-io/sdk-go/pkg/api/client/send_transactions"
	"github.com/0xkey-io/sdk-go/pkg/api/client/sessions"
	"github.com/0xkey-io/sdk-go/pkg/api/client/signing"
	"github.com/0xkey-io/sdk-go/pkg/api/client/user_auth"
	"github.com/0xkey-io/sdk-go/pkg/api/client/user_recovery"
	"github.com/0xkey-io/sdk-go/pkg/api/client/user_tags"
	"github.com/0xkey-io/sdk-go/pkg/api/client/user_verification"
	"github.com/0xkey-io/sdk-go/pkg/api/client/users"
	"github.com/0xkey-io/sdk-go/pkg/api/client/wallets"
)

// Default 0xkey API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.0xkey.io"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new 0xkey API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *ZeroXKeyAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new 0xkey API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *ZeroXKeyAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new 0xkey API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *ZeroXKeyAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(ZeroXKeyAPI)
	cli.Transport = transport
	cli.Activities = activities.New(transport, formats)
	cli.APIKeys = api_keys.New(transport, formats)
	cli.AppProof = app_proof.New(transport, formats)
	cli.Authenticators = authenticators.New(transport, formats)
	cli.BootProof = boot_proof.New(transport, formats)
	cli.Broadcasting = broadcasting.New(transport, formats)
	cli.Consensus = consensus.New(transport, formats)
	cli.Features = features.New(transport, formats)
	cli.Invitations = invitations.New(transport, formats)
	cli.OnRamp = on_ramp.New(transport, formats)
	cli.Operations = operations.New(transport, formats)
	cli.Organizations = organizations.New(transport, formats)
	cli.Policies = policies.New(transport, formats)
	cli.PrivateKeyTags = private_key_tags.New(transport, formats)
	cli.PrivateKeys = private_keys.New(transport, formats)
	cli.SendTransactions = send_transactions.New(transport, formats)
	cli.Sessions = sessions.New(transport, formats)
	cli.Signing = signing.New(transport, formats)
	cli.UserAuth = user_auth.New(transport, formats)
	cli.UserRecovery = user_recovery.New(transport, formats)
	cli.UserTags = user_tags.New(transport, formats)
	cli.UserVerification = user_verification.New(transport, formats)
	cli.Users = users.New(transport, formats)
	cli.Wallets = wallets.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// ZeroXKeyAPI is a client for 0xkey API
type ZeroXKeyAPI struct {
	Activities activities.ClientService

	APIKeys api_keys.ClientService

	AppProof app_proof.ClientService

	Authenticators authenticators.ClientService

	BootProof boot_proof.ClientService

	Broadcasting broadcasting.ClientService

	Consensus consensus.ClientService

	Features features.ClientService

	Invitations invitations.ClientService

	OnRamp on_ramp.ClientService

	Operations operations.ClientService

	Organizations organizations.ClientService

	Policies policies.ClientService

	PrivateKeyTags private_key_tags.ClientService

	PrivateKeys private_keys.ClientService

	SendTransactions send_transactions.ClientService

	Sessions sessions.ClientService

	Signing signing.ClientService

	UserAuth user_auth.ClientService

	UserRecovery user_recovery.ClientService

	UserTags user_tags.ClientService

	UserVerification user_verification.ClientService

	Users users.ClientService

	Wallets wallets.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *ZeroXKeyAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Activities.SetTransport(transport)
	c.APIKeys.SetTransport(transport)
	c.AppProof.SetTransport(transport)
	c.Authenticators.SetTransport(transport)
	c.BootProof.SetTransport(transport)
	c.Broadcasting.SetTransport(transport)
	c.Consensus.SetTransport(transport)
	c.Features.SetTransport(transport)
	c.Invitations.SetTransport(transport)
	c.OnRamp.SetTransport(transport)
	c.Operations.SetTransport(transport)
	c.Organizations.SetTransport(transport)
	c.Policies.SetTransport(transport)
	c.PrivateKeyTags.SetTransport(transport)
	c.PrivateKeys.SetTransport(transport)
	c.SendTransactions.SetTransport(transport)
	c.Sessions.SetTransport(transport)
	c.Signing.SetTransport(transport)
	c.UserAuth.SetTransport(transport)
	c.UserRecovery.SetTransport(transport)
	c.UserTags.SetTransport(transport)
	c.UserVerification.SetTransport(transport)
	c.Users.SetTransport(transport)
	c.Wallets.SetTransport(transport)
}
