// Code generated by go-swagger; DO NOT EDIT.

package session_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewCreateSessionProfileParams creates a new CreateSessionProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSessionProfileParams() *CreateSessionProfileParams {
	return &CreateSessionProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSessionProfileParamsWithTimeout creates a new CreateSessionProfileParams object
// with the ability to set a timeout on a request.
func NewCreateSessionProfileParamsWithTimeout(timeout time.Duration) *CreateSessionProfileParams {
	return &CreateSessionProfileParams{
		timeout: timeout,
	}
}

// NewCreateSessionProfileParamsWithContext creates a new CreateSessionProfileParams object
// with the ability to set a context for a request.
func NewCreateSessionProfileParamsWithContext(ctx context.Context) *CreateSessionProfileParams {
	return &CreateSessionProfileParams{
		Context: ctx,
	}
}

// NewCreateSessionProfileParamsWithHTTPClient creates a new CreateSessionProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSessionProfileParamsWithHTTPClient(client *http.Client) *CreateSessionProfileParams {
	return &CreateSessionProfileParams{
		HTTPClient: client,
	}
}

/*
CreateSessionProfileParams contains all the parameters to send to the API endpoint

	for the create session profile operation.

	Typically these are written to a http.Request.
*/
type CreateSessionProfileParams struct {

	// Body.
	Body *models.CreateSessionProfileRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create session profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSessionProfileParams) WithDefaults() *CreateSessionProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create session profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSessionProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create session profile params
func (o *CreateSessionProfileParams) WithTimeout(timeout time.Duration) *CreateSessionProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create session profile params
func (o *CreateSessionProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create session profile params
func (o *CreateSessionProfileParams) WithContext(ctx context.Context) *CreateSessionProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create session profile params
func (o *CreateSessionProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create session profile params
func (o *CreateSessionProfileParams) WithHTTPClient(client *http.Client) *CreateSessionProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create session profile params
func (o *CreateSessionProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create session profile params
func (o *CreateSessionProfileParams) WithBody(body *models.CreateSessionProfileRequest) *CreateSessionProfileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create session profile params
func (o *CreateSessionProfileParams) SetBody(body *models.CreateSessionProfileRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSessionProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
