// Code generated by go-swagger; DO NOT EDIT.

package session_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// GetSessionProfileReader is a Reader for the GetSessionProfile structure.
type GetSessionProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSessionProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSessionProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/query/get_session_profile] GetSessionProfile", response, response.Code())
	}
}

// NewGetSessionProfileOK creates a GetSessionProfileOK with default headers values
func NewGetSessionProfileOK() *GetSessionProfileOK {
	return &GetSessionProfileOK{}
}

/*
GetSessionProfileOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetSessionProfileOK struct {
	Payload *models.GetSessionProfileResponse
}

// IsSuccess returns true when this get session profile o k response has a 2xx status code
func (o *GetSessionProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get session profile o k response has a 3xx status code
func (o *GetSessionProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get session profile o k response has a 4xx status code
func (o *GetSessionProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get session profile o k response has a 5xx status code
func (o *GetSessionProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get session profile o k response a status code equal to that given
func (o *GetSessionProfileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get session profile o k response
func (o *GetSessionProfileOK) Code() int {
	return 200
}

func (o *GetSessionProfileOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_session_profile][%d] getSessionProfileOK  %+v", 200, o.Payload)
}

func (o *GetSessionProfileOK) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_session_profile][%d] getSessionProfileOK  %+v", 200, o.Payload)
}

func (o *GetSessionProfileOK) GetPayload() *models.GetSessionProfileResponse {
	return o.Payload
}

func (o *GetSessionProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetSessionProfileResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
