// Code generated by go-swagger; DO NOT EDIT.

package session_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewGetSessionProfileParams creates a new GetSessionProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSessionProfileParams() *GetSessionProfileParams {
	return &GetSessionProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSessionProfileParamsWithTimeout creates a new GetSessionProfileParams object
// with the ability to set a timeout on a request.
func NewGetSessionProfileParamsWithTimeout(timeout time.Duration) *GetSessionProfileParams {
	return &GetSessionProfileParams{
		timeout: timeout,
	}
}

// NewGetSessionProfileParamsWithContext creates a new GetSessionProfileParams object
// with the ability to set a context for a request.
func NewGetSessionProfileParamsWithContext(ctx context.Context) *GetSessionProfileParams {
	return &GetSessionProfileParams{
		Context: ctx,
	}
}

// NewGetSessionProfileParamsWithHTTPClient creates a new GetSessionProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSessionProfileParamsWithHTTPClient(client *http.Client) *GetSessionProfileParams {
	return &GetSessionProfileParams{
		HTTPClient: client,
	}
}

/*
GetSessionProfileParams contains all the parameters to send to the API endpoint

	for the get session profile operation.

	Typically these are written to a http.Request.
*/
type GetSessionProfileParams struct {

	// Body.
	Body *models.GetSessionProfileRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get session profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionProfileParams) WithDefaults() *GetSessionProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get session profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get session profile params
func (o *GetSessionProfileParams) WithTimeout(timeout time.Duration) *GetSessionProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get session profile params
func (o *GetSessionProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get session profile params
func (o *GetSessionProfileParams) WithContext(ctx context.Context) *GetSessionProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get session profile params
func (o *GetSessionProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get session profile params
func (o *GetSessionProfileParams) WithHTTPClient(client *http.Client) *GetSessionProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get session profile params
func (o *GetSessionProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get session profile params
func (o *GetSessionProfileParams) WithBody(body *models.GetSessionProfileRequest) *GetSessionProfileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get session profile params
func (o *GetSessionProfileParams) SetBody(body *models.GetSessionProfileRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetSessionProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
