// Code generated by go-swagger; DO NOT EDIT.

package session_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// GetSessionProfilesReader is a Reader for the GetSessionProfiles structure.
type GetSessionProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSessionProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSessionProfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /public/v1/query/get_session_profiles] GetSessionProfiles", response, response.Code())
	}
}

// NewGetSessionProfilesOK creates a GetSessionProfilesOK with default headers values
func NewGetSessionProfilesOK() *GetSessionProfilesOK {
	return &GetSessionProfilesOK{}
}

/*
GetSessionProfilesOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetSessionProfilesOK struct {
	Payload *models.GetSessionProfilesResponse
}

// IsSuccess returns true when this get session profiles o k response has a 2xx status code
func (o *GetSessionProfilesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get session profiles o k response has a 3xx status code
func (o *GetSessionProfilesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get session profiles o k response has a 4xx status code
func (o *GetSessionProfilesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get session profiles o k response has a 5xx status code
func (o *GetSessionProfilesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get session profiles o k response a status code equal to that given
func (o *GetSessionProfilesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get session profiles o k response
func (o *GetSessionProfilesOK) Code() int {
	return 200
}

func (o *GetSessionProfilesOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_session_profiles][%d] getSessionProfilesOK  %+v", 200, o.Payload)
}

func (o *GetSessionProfilesOK) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_session_profiles][%d] getSessionProfilesOK  %+v", 200, o.Payload)
}

func (o *GetSessionProfilesOK) GetPayload() *models.GetSessionProfilesResponse {
	return o.Payload
}

func (o *GetSessionProfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetSessionProfilesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
