// Code generated by go-swagger; DO NOT EDIT.

package session_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewGetSessionProfilesParams creates a new GetSessionProfilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSessionProfilesParams() *GetSessionProfilesParams {
	return &GetSessionProfilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSessionProfilesParamsWithTimeout creates a new GetSessionProfilesParams object
// with the ability to set a timeout on a request.
func NewGetSessionProfilesParamsWithTimeout(timeout time.Duration) *GetSessionProfilesParams {
	return &GetSessionProfilesParams{
		timeout: timeout,
	}
}

// NewGetSessionProfilesParamsWithContext creates a new GetSessionProfilesParams object
// with the ability to set a context for a request.
func NewGetSessionProfilesParamsWithContext(ctx context.Context) *GetSessionProfilesParams {
	return &GetSessionProfilesParams{
		Context: ctx,
	}
}

// NewGetSessionProfilesParamsWithHTTPClient creates a new GetSessionProfilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSessionProfilesParamsWithHTTPClient(client *http.Client) *GetSessionProfilesParams {
	return &GetSessionProfilesParams{
		HTTPClient: client,
	}
}

/*
GetSessionProfilesParams contains all the parameters to send to the API endpoint

	for the get session profiles operation.

	Typically these are written to a http.Request.
*/
type GetSessionProfilesParams struct {

	// Body.
	Body *models.GetSessionProfilesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get session profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionProfilesParams) WithDefaults() *GetSessionProfilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get session profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionProfilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get session profiles params
func (o *GetSessionProfilesParams) WithTimeout(timeout time.Duration) *GetSessionProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get session profiles params
func (o *GetSessionProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get session profiles params
func (o *GetSessionProfilesParams) WithContext(ctx context.Context) *GetSessionProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get session profiles params
func (o *GetSessionProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get session profiles params
func (o *GetSessionProfilesParams) WithHTTPClient(client *http.Client) *GetSessionProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get session profiles params
func (o *GetSessionProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get session profiles params
func (o *GetSessionProfilesParams) WithBody(body *models.GetSessionProfilesRequest) *GetSessionProfilesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get session profiles params
func (o *GetSessionProfilesParams) SetBody(body *models.GetSessionProfilesRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetSessionProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
