// Code generated by go-swagger; DO NOT EDIT.

package session_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new session profiles API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for session profiles API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateSessionProfile(params *CreateSessionProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateSessionProfileOK, error)

	GetSessionProfile(params *GetSessionProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetSessionProfileOK, error)

	GetSessionProfiles(params *GetSessionProfilesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetSessionProfilesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateSessionProfile creates session profile

Create a new session profile for an organization.
*/
func (a *Client) CreateSessionProfile(params *CreateSessionProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateSessionProfileOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateSessionProfileParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateSessionProfile",
		Method:             "POST",
		PathPattern:        "/public/v1/submit/create_session_profile",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateSessionProfileReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateSessionProfileOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateSessionProfile: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSessionProfile gets session profile

Get one session profile for an organization.
*/
func (a *Client) GetSessionProfile(params *GetSessionProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetSessionProfileOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSessionProfileParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSessionProfile",
		Method:             "POST",
		PathPattern:        "/public/v1/query/get_session_profile",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetSessionProfileReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetSessionProfileOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSessionProfile: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSessionProfiles gets session profiles

Get all session profiles for an organization.
*/
func (a *Client) GetSessionProfiles(params *GetSessionProfilesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetSessionProfilesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSessionProfilesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSessionProfiles",
		Method:             "POST",
		PathPattern:        "/public/v1/query/get_session_profiles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetSessionProfilesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetSessionProfilesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSessionProfiles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
