// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AuthenticationType authentication type
//
// swagger:model AuthenticationType
type AuthenticationType string

func NewAuthenticationType(value AuthenticationType) *AuthenticationType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AuthenticationType.
func (m AuthenticationType) Pointer() *AuthenticationType {
	return &m
}

const (

	// AuthenticationTypeUnspecified captures enum value "AUTHENTICATION_TYPE_UNSPECIFIED"
	AuthenticationTypeUnspecified AuthenticationType = "AUTHENTICATION_TYPE_UNSPECIFIED"

	// AuthenticationTypeEmailOtp captures enum value "AUTHENTICATION_TYPE_EMAIL_OTP"
	AuthenticationTypeEmailOtp AuthenticationType = "AUTHENTICATION_TYPE_EMAIL_OTP"

	// AuthenticationTypeSmsOtp captures enum value "AUTHENTICATION_TYPE_SMS_OTP"
	AuthenticationTypeSmsOtp AuthenticationType = "AUTHENTICATION_TYPE_SMS_OTP"

	// AuthenticationTypePasskey captures enum value "AUTHENTICATION_TYPE_PASSKEY"
	AuthenticationTypePasskey AuthenticationType = "AUTHENTICATION_TYPE_PASSKEY"

	// AuthenticationTypeAPIKey captures enum value "AUTHENTICATION_TYPE_API_KEY"
	AuthenticationTypeAPIKey AuthenticationType = "AUTHENTICATION_TYPE_API_KEY"

	// AuthenticationTypeOauth captures enum value "AUTHENTICATION_TYPE_OAUTH"
	AuthenticationTypeOauth AuthenticationType = "AUTHENTICATION_TYPE_OAUTH"

	// AuthenticationTypeSession captures enum value "AUTHENTICATION_TYPE_SESSION"
	AuthenticationTypeSession AuthenticationType = "AUTHENTICATION_TYPE_SESSION"
)

// for schema
var AuthenticationTypeEnum []AuthenticationType

func init() {
	var res []AuthenticationType
	if err := json.Unmarshal([]byte(`["AUTHENTICATION_TYPE_UNSPECIFIED","AUTHENTICATION_TYPE_EMAIL_OTP","AUTHENTICATION_TYPE_SMS_OTP","AUTHENTICATION_TYPE_PASSKEY","AUTHENTICATION_TYPE_API_KEY","AUTHENTICATION_TYPE_OAUTH","AUTHENTICATION_TYPE_SESSION"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		AuthenticationTypeEnum = append(AuthenticationTypeEnum, v)
	}
}

func (m AuthenticationType) validateAuthenticationTypeEnum(path, location string, value AuthenticationType) error {
	if err := validate.EnumCase(path, location, value, AuthenticationTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this authentication type
func (m AuthenticationType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAuthenticationTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this authentication type based on context it is used
func (m AuthenticationType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
