// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateSessionProfileIntent create session profile intent
//
// swagger:model CreateSessionProfileIntent
type CreateSessionProfileIntent struct {

	// expiration seconds
	ExpirationSeconds string `json:"expirationSeconds,omitempty"`

	// notes
	Notes string `json:"notes,omitempty"`

	// scope
	// Required: true
	Scope *string `json:"scope"`

	// session profile name
	// Required: true
	SessionProfileName *string `json:"sessionProfileName"`
}

// Validate validates this create session profile intent
func (m *CreateSessionProfileIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionProfileName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSessionProfileIntent) validateScope(formats strfmt.Registry) error {

	if err := validate.Required("scope", "body", m.Scope); err != nil {
		return err
	}

	return nil
}

func (m *CreateSessionProfileIntent) validateSessionProfileName(formats strfmt.Registry) error {

	if err := validate.Required("sessionProfileName", "body", m.SessionProfileName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create session profile intent based on context it is used
func (m *CreateSessionProfileIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSessionProfileIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSessionProfileIntent) UnmarshalBinary(b []byte) error {
	var res CreateSessionProfileIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
