// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateMfaPolicyIntent create mfa policy intent
//
// swagger:model CreateMfaPolicyIntent
type CreateMfaPolicyIntent struct {

	// condition
	// Required: true
	Condition *string `json:"condition"`

	// mfa policy name
	// Required: true
	MfaPolicyName *string `json:"mfaPolicyName"`

	// notes
	Notes string `json:"notes,omitempty"`

	// order
	// Required: true
	Order *int64 `json:"order"`

	// required authentication methods
	// Required: true
	RequiredAuthenticationMethods []*RequiredAuthenticationMethodParams `json:"requiredAuthenticationMethods"`

	// user Id
	// Required: true
	UserID *string `json:"userId"`
}

// Validate validates this create mfa policy intent
func (m *CreateMfaPolicyIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCondition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMfaPolicyName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrder(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequiredAuthenticationMethods(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateMfaPolicyIntent) validateCondition(formats strfmt.Registry) error {

	if err := validate.Required("condition", "body", m.Condition); err != nil {
		return err
	}

	return nil
}

func (m *CreateMfaPolicyIntent) validateMfaPolicyName(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicyName", "body", m.MfaPolicyName); err != nil {
		return err
	}

	return nil
}

func (m *CreateMfaPolicyIntent) validateOrder(formats strfmt.Registry) error {

	if err := validate.Required("order", "body", m.Order); err != nil {
		return err
	}

	return nil
}

func (m *CreateMfaPolicyIntent) validateRequiredAuthenticationMethods(formats strfmt.Registry) error {

	if err := validate.Required("requiredAuthenticationMethods", "body", m.RequiredAuthenticationMethods); err != nil {
		return err
	}

	for i := 0; i < len(m.RequiredAuthenticationMethods); i++ {
		if swag.IsZero(m.RequiredAuthenticationMethods[i]) { // not required
			continue
		}

		if m.RequiredAuthenticationMethods[i] != nil {
			if err := m.RequiredAuthenticationMethods[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CreateMfaPolicyIntent) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("userId", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this create mfa policy intent based on the context it is used
func (m *CreateMfaPolicyIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRequiredAuthenticationMethods(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateMfaPolicyIntent) contextValidateRequiredAuthenticationMethods(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RequiredAuthenticationMethods); i++ {

		if m.RequiredAuthenticationMethods[i] != nil {

			if swag.IsZero(m.RequiredAuthenticationMethods[i]) { // not required
				return nil
			}

			if err := m.RequiredAuthenticationMethods[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateMfaPolicyIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateMfaPolicyIntent) UnmarshalBinary(b []byte) error {
	var res CreateMfaPolicyIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
