// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteMfaPolicyIntent delete mfa policy intent
//
// swagger:model DeleteMfaPolicyIntent
type DeleteMfaPolicyIntent struct {

	// mfa policy Id
	// Required: true
	MfaPolicyID *string `json:"mfaPolicyId"`

	// user Id
	// Required: true
	UserID *string `json:"userId"`
}

// Validate validates this delete mfa policy intent
func (m *DeleteMfaPolicyIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMfaPolicyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteMfaPolicyIntent) validateMfaPolicyID(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicyId", "body", m.MfaPolicyID); err != nil {
		return err
	}

	return nil
}

func (m *DeleteMfaPolicyIntent) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("userId", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete mfa policy intent based on context it is used
func (m *DeleteMfaPolicyIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteMfaPolicyIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteMfaPolicyIntent) UnmarshalBinary(b []byte) error {
	var res DeleteMfaPolicyIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
