// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetMfaStatusResponse get mfa status response
//
// swagger:model GetMfaStatusResponse
type GetMfaStatusResponse struct {

	// mfa statuses
	// Required: true
	MfaStatuses []*MfaStatus `json:"mfaStatuses"`
}

// Validate validates this get mfa status response
func (m *GetMfaStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMfaStatuses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetMfaStatusResponse) validateMfaStatuses(formats strfmt.Registry) error {

	if err := validate.Required("mfaStatuses", "body", m.MfaStatuses); err != nil {
		return err
	}

	for i := 0; i < len(m.MfaStatuses); i++ {
		if swag.IsZero(m.MfaStatuses[i]) { // not required
			continue
		}

		if m.MfaStatuses[i] != nil {
			if err := m.MfaStatuses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mfaStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("mfaStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get mfa status response based on the context it is used
func (m *GetMfaStatusResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMfaStatuses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetMfaStatusResponse) contextValidateMfaStatuses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.MfaStatuses); i++ {

		if m.MfaStatuses[i] != nil {

			if swag.IsZero(m.MfaStatuses[i]) { // not required
				return nil
			}

			if err := m.MfaStatuses[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mfaStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("mfaStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetMfaStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetMfaStatusResponse) UnmarshalBinary(b []byte) error {
	var res GetMfaStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
