// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetMfaPolicyResponse get mfa policy response
//
// swagger:model GetMfaPolicyResponse
type GetMfaPolicyResponse struct {

	// mfa policy
	// Required: true
	MfaPolicy *MfaPolicy `json:"mfaPolicy"`
}

// Validate validates this get mfa policy response
func (m *GetMfaPolicyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMfaPolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetMfaPolicyResponse) validateMfaPolicy(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicy", "body", m.MfaPolicy); err != nil {
		return err
	}

	if m.MfaPolicy != nil {
		if err := m.MfaPolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mfaPolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("mfaPolicy")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get mfa policy response based on the context it is used
func (m *GetMfaPolicyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMfaPolicy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetMfaPolicyResponse) contextValidateMfaPolicy(ctx context.Context, formats strfmt.Registry) error {

	if m.MfaPolicy != nil {

		if err := m.MfaPolicy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mfaPolicy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("mfaPolicy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetMfaPolicyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetMfaPolicyResponse) UnmarshalBinary(b []byte) error {
	var res GetMfaPolicyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
