// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetSessionProfileRequest get session profile request
//
// swagger:model GetSessionProfileRequest
type GetSessionProfileRequest struct {

	// organization Id
	// Required: true
	OrganizationID *string `json:"organizationId"`

	// session profile Id
	// Required: true
	SessionProfileID *string `json:"sessionProfileId"`
}

// Validate validates this get session profile request
func (m *GetSessionProfileRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrganizationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionProfileID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSessionProfileRequest) validateOrganizationID(formats strfmt.Registry) error {

	if err := validate.Required("organizationId", "body", m.OrganizationID); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionProfileRequest) validateSessionProfileID(formats strfmt.Registry) error {

	if err := validate.Required("sessionProfileId", "body", m.SessionProfileID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get session profile request based on context it is used
func (m *GetSessionProfileRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetSessionProfileRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSessionProfileRequest) UnmarshalBinary(b []byte) error {
	var res GetSessionProfileRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
