// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetSessionProfileResponse get session profile response
//
// swagger:model GetSessionProfileResponse
type GetSessionProfileResponse struct {

	// session profile
	// Required: true
	SessionProfile *SessionProfile `json:"sessionProfile"`
}

// Validate validates this get session profile response
func (m *GetSessionProfileResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSessionProfile(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSessionProfileResponse) validateSessionProfile(formats strfmt.Registry) error {

	if err := validate.Required("sessionProfile", "body", m.SessionProfile); err != nil {
		return err
	}

	if m.SessionProfile != nil {
		if err := m.SessionProfile.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sessionProfile")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sessionProfile")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get session profile response based on the context it is used
func (m *GetSessionProfileResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSessionProfile(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSessionProfileResponse) contextValidateSessionProfile(ctx context.Context, formats strfmt.Registry) error {

	if m.SessionProfile != nil {

		if err := m.SessionProfile.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sessionProfile")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sessionProfile")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetSessionProfileResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSessionProfileResponse) UnmarshalBinary(b []byte) error {
	var res GetSessionProfileResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
