// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetMfaPoliciesResponse get mfa policies response
//
// swagger:model GetMfaPoliciesResponse
type GetMfaPoliciesResponse struct {

	// mfa policies
	// Required: true
	MfaPolicies []*MfaPolicy `json:"mfaPolicies"`
}

// Validate validates this get mfa policies response
func (m *GetMfaPoliciesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMfaPolicies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetMfaPoliciesResponse) validateMfaPolicies(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicies", "body", m.MfaPolicies); err != nil {
		return err
	}

	for i := 0; i < len(m.MfaPolicies); i++ {
		if swag.IsZero(m.MfaPolicies[i]) { // not required
			continue
		}

		if m.MfaPolicies[i] != nil {
			if err := m.MfaPolicies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mfaPolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("mfaPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get mfa policies response based on the context it is used
func (m *GetMfaPoliciesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMfaPolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetMfaPoliciesResponse) contextValidateMfaPolicies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.MfaPolicies); i++ {

		if m.MfaPolicies[i] != nil {

			if swag.IsZero(m.MfaPolicies[i]) { // not required
				return nil
			}

			if err := m.MfaPolicies[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mfaPolicies" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("mfaPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetMfaPoliciesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetMfaPoliciesResponse) UnmarshalBinary(b []byte) error {
	var res GetMfaPoliciesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
