// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetMfaPolicyRequest get mfa policy request
//
// swagger:model GetMfaPolicyRequest
type GetMfaPolicyRequest struct {

	// mfa policy Id
	// Required: true
	MfaPolicyID *string `json:"mfaPolicyId"`

	// organization Id
	// Required: true
	OrganizationID *string `json:"organizationId"`

	// user Id
	// Required: true
	UserID *string `json:"userId"`
}

// Validate validates this get mfa policy request
func (m *GetMfaPolicyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMfaPolicyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganizationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetMfaPolicyRequest) validateMfaPolicyID(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicyId", "body", m.MfaPolicyID); err != nil {
		return err
	}

	return nil
}

func (m *GetMfaPolicyRequest) validateOrganizationID(formats strfmt.Registry) error {

	if err := validate.Required("organizationId", "body", m.OrganizationID); err != nil {
		return err
	}

	return nil
}

func (m *GetMfaPolicyRequest) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("userId", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get mfa policy request based on context it is used
func (m *GetMfaPolicyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetMfaPolicyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetMfaPolicyRequest) UnmarshalBinary(b []byte) error {
	var res GetMfaPolicyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
