// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetSessionProfilesResponse get session profiles response
//
// swagger:model GetSessionProfilesResponse
type GetSessionProfilesResponse struct {

	// session profiles
	// Required: true
	SessionProfiles []*SessionProfile `json:"sessionProfiles"`
}

// Validate validates this get session profiles response
func (m *GetSessionProfilesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSessionProfiles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSessionProfilesResponse) validateSessionProfiles(formats strfmt.Registry) error {

	if err := validate.Required("sessionProfiles", "body", m.SessionProfiles); err != nil {
		return err
	}

	for i := 0; i < len(m.SessionProfiles); i++ {
		if swag.IsZero(m.SessionProfiles[i]) { // not required
			continue
		}

		if m.SessionProfiles[i] != nil {
			if err := m.SessionProfiles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sessionProfiles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sessionProfiles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get session profiles response based on the context it is used
func (m *GetSessionProfilesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSessionProfiles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSessionProfilesResponse) contextValidateSessionProfiles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SessionProfiles); i++ {

		if m.SessionProfiles[i] != nil {

			if swag.IsZero(m.SessionProfiles[i]) { // not required
				return nil
			}

			if err := m.SessionProfiles[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sessionProfiles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sessionProfiles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetSessionProfilesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSessionProfilesResponse) UnmarshalBinary(b []byte) error {
	var res GetSessionProfilesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
