// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MfaStatus mfa status
//
// swagger:model MfaStatus
type MfaStatus struct {

	// mfa policy Id
	// Required: true
	MfaPolicyID *string `json:"mfaPolicyId"`

	// required methods
	// Required: true
	RequiredMethods []*RequiredAuthenticationMethod `json:"requiredMethods"`

	// satisfied
	// Required: true
	Satisfied *bool `json:"satisfied"`

	// satisfied methods
	// Required: true
	SatisfiedMethods []*AuthenticationMethod `json:"satisfiedMethods"`

	// user Id
	// Required: true
	UserID *string `json:"userId"`
}

// Validate validates this mfa status
func (m *MfaStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMfaPolicyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequiredMethods(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSatisfied(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSatisfiedMethods(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MfaStatus) validateMfaPolicyID(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicyId", "body", m.MfaPolicyID); err != nil {
		return err
	}

	return nil
}

func (m *MfaStatus) validateRequiredMethods(formats strfmt.Registry) error {

	if err := validate.Required("requiredMethods", "body", m.RequiredMethods); err != nil {
		return err
	}

	for i := 0; i < len(m.RequiredMethods); i++ {
		if swag.IsZero(m.RequiredMethods[i]) { // not required
			continue
		}

		if m.RequiredMethods[i] != nil {
			if err := m.RequiredMethods[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requiredMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requiredMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *MfaStatus) validateSatisfied(formats strfmt.Registry) error {

	if err := validate.Required("satisfied", "body", m.Satisfied); err != nil {
		return err
	}

	return nil
}

func (m *MfaStatus) validateSatisfiedMethods(formats strfmt.Registry) error {

	if err := validate.Required("satisfiedMethods", "body", m.SatisfiedMethods); err != nil {
		return err
	}

	for i := 0; i < len(m.SatisfiedMethods); i++ {
		if swag.IsZero(m.SatisfiedMethods[i]) { // not required
			continue
		}

		if m.SatisfiedMethods[i] != nil {
			if err := m.SatisfiedMethods[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("satisfiedMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("satisfiedMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *MfaStatus) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("userId", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this mfa status based on the context it is used
func (m *MfaStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRequiredMethods(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSatisfiedMethods(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MfaStatus) contextValidateRequiredMethods(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RequiredMethods); i++ {

		if m.RequiredMethods[i] != nil {

			if swag.IsZero(m.RequiredMethods[i]) { // not required
				return nil
			}

			if err := m.RequiredMethods[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requiredMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requiredMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *MfaStatus) contextValidateSatisfiedMethods(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SatisfiedMethods); i++ {

		if m.SatisfiedMethods[i] != nil {

			if swag.IsZero(m.SatisfiedMethods[i]) { // not required
				return nil
			}

			if err := m.SatisfiedMethods[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("satisfiedMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("satisfiedMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MfaStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MfaStatus) UnmarshalBinary(b []byte) error {
	var res MfaStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
