// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MfaPolicy mfa policy
//
// swagger:model MfaPolicy
type MfaPolicy struct {

	// condition
	// Required: true
	Condition *string `json:"condition"`

	// created at
	// Required: true
	CreatedAt *Timestamp `json:"createdAt"`

	// mfa policy Id
	// Required: true
	MfaPolicyID *string `json:"mfaPolicyId"`

	// mfa policy name
	// Required: true
	MfaPolicyName *string `json:"mfaPolicyName"`

	// notes
	Notes string `json:"notes,omitempty"`

	// order
	// Required: true
	Order *int64 `json:"order"`

	// required authentication methods
	// Required: true
	RequiredAuthenticationMethods []*RequiredAuthenticationMethod `json:"requiredAuthenticationMethods"`

	// updated at
	// Required: true
	UpdatedAt *Timestamp `json:"updatedAt"`
}

// Validate validates this mfa policy
func (m *MfaPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCondition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMfaPolicyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMfaPolicyName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrder(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequiredAuthenticationMethods(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MfaPolicy) validateCondition(formats strfmt.Registry) error {

	if err := validate.Required("condition", "body", m.Condition); err != nil {
		return err
	}

	return nil
}

func (m *MfaPolicy) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("createdAt", "body", m.CreatedAt); err != nil {
		return err
	}

	if m.CreatedAt != nil {
		if err := m.CreatedAt.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdAt")
			}
			return err
		}
	}

	return nil
}

func (m *MfaPolicy) validateMfaPolicyID(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicyId", "body", m.MfaPolicyID); err != nil {
		return err
	}

	return nil
}

func (m *MfaPolicy) validateMfaPolicyName(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicyName", "body", m.MfaPolicyName); err != nil {
		return err
	}

	return nil
}

func (m *MfaPolicy) validateOrder(formats strfmt.Registry) error {

	if err := validate.Required("order", "body", m.Order); err != nil {
		return err
	}

	return nil
}

func (m *MfaPolicy) validateRequiredAuthenticationMethods(formats strfmt.Registry) error {

	if err := validate.Required("requiredAuthenticationMethods", "body", m.RequiredAuthenticationMethods); err != nil {
		return err
	}

	for i := 0; i < len(m.RequiredAuthenticationMethods); i++ {
		if swag.IsZero(m.RequiredAuthenticationMethods[i]) { // not required
			continue
		}

		if m.RequiredAuthenticationMethods[i] != nil {
			if err := m.RequiredAuthenticationMethods[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *MfaPolicy) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("updatedAt", "body", m.UpdatedAt); err != nil {
		return err
	}

	if m.UpdatedAt != nil {
		if err := m.UpdatedAt.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updatedAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updatedAt")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this mfa policy based on the context it is used
func (m *MfaPolicy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRequiredAuthenticationMethods(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MfaPolicy) contextValidateCreatedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedAt != nil {

		if err := m.CreatedAt.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdAt")
			}
			return err
		}
	}

	return nil
}

func (m *MfaPolicy) contextValidateRequiredAuthenticationMethods(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RequiredAuthenticationMethods); i++ {

		if m.RequiredAuthenticationMethods[i] != nil {

			if swag.IsZero(m.RequiredAuthenticationMethods[i]) { // not required
				return nil
			}

			if err := m.RequiredAuthenticationMethods[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *MfaPolicy) contextValidateUpdatedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.UpdatedAt != nil {

		if err := m.UpdatedAt.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updatedAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updatedAt")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MfaPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MfaPolicy) UnmarshalBinary(b []byte) error {
	var res MfaPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
