// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RequiredAuthenticationMethod required authentication method
//
// swagger:model RequiredAuthenticationMethod
type RequiredAuthenticationMethod struct {

	// any
	// Required: true
	Any []*AuthenticationMethod `json:"any"`
}

// Validate validates this required authentication method
func (m *RequiredAuthenticationMethod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAny(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequiredAuthenticationMethod) validateAny(formats strfmt.Registry) error {

	if err := validate.Required("any", "body", m.Any); err != nil {
		return err
	}

	for i := 0; i < len(m.Any); i++ {
		if swag.IsZero(m.Any[i]) { // not required
			continue
		}

		if m.Any[i] != nil {
			if err := m.Any[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("any" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("any" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this required authentication method based on the context it is used
func (m *RequiredAuthenticationMethod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAny(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequiredAuthenticationMethod) contextValidateAny(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Any); i++ {

		if m.Any[i] != nil {

			if swag.IsZero(m.Any[i]) { // not required
				return nil
			}

			if err := m.Any[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("any" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("any" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RequiredAuthenticationMethod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequiredAuthenticationMethod) UnmarshalBinary(b []byte) error {
	var res RequiredAuthenticationMethod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
