// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateMfaPolicyIntent update mfa policy intent
//
// swagger:model UpdateMfaPolicyIntent
type UpdateMfaPolicyIntent struct {

	// condition
	Condition string `json:"condition,omitempty"`

	// mfa policy Id
	// Required: true
	MfaPolicyID *string `json:"mfaPolicyId"`

	// mfa policy name
	MfaPolicyName string `json:"mfaPolicyName,omitempty"`

	// notes
	Notes string `json:"notes,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// required authentication methods
	RequiredAuthenticationMethods []*RequiredAuthenticationMethodParams `json:"requiredAuthenticationMethods"`

	// user Id
	// Required: true
	UserID *string `json:"userId"`
}

// Validate validates this update mfa policy intent
func (m *UpdateMfaPolicyIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMfaPolicyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequiredAuthenticationMethods(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateMfaPolicyIntent) validateMfaPolicyID(formats strfmt.Registry) error {

	if err := validate.Required("mfaPolicyId", "body", m.MfaPolicyID); err != nil {
		return err
	}

	return nil
}

func (m *UpdateMfaPolicyIntent) validateRequiredAuthenticationMethods(formats strfmt.Registry) error {
	if swag.IsZero(m.RequiredAuthenticationMethods) { // not required
		return nil
	}

	for i := 0; i < len(m.RequiredAuthenticationMethods); i++ {
		if swag.IsZero(m.RequiredAuthenticationMethods[i]) { // not required
			continue
		}

		if m.RequiredAuthenticationMethods[i] != nil {
			if err := m.RequiredAuthenticationMethods[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UpdateMfaPolicyIntent) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("userId", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this update mfa policy intent based on the context it is used
func (m *UpdateMfaPolicyIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRequiredAuthenticationMethods(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateMfaPolicyIntent) contextValidateRequiredAuthenticationMethods(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RequiredAuthenticationMethods); i++ {

		if m.RequiredAuthenticationMethods[i] != nil {

			if swag.IsZero(m.RequiredAuthenticationMethods[i]) { // not required
				return nil
			}

			if err := m.RequiredAuthenticationMethods[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("requiredAuthenticationMethods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateMfaPolicyIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateMfaPolicyIntent) UnmarshalBinary(b []byte) error {
	var res UpdateMfaPolicyIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
