// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1GetAttestationDocumentRequest v1 get attestation document request
//
// swagger:model v1GetAttestationDocumentRequest
type V1GetAttestationDocumentRequest struct {

	// Enclave app to attest. Accepted values (case-insensitive): signer; notarizer; tls-fetcher|fetcher; evm-parser|transaction-parser|parser; ump|policy-engine|policy. Turnkey alias `ump` maps to 0xkey `policy-engine`.
	// Required: true
	EnclaveType *string `json:"enclaveType"`

	// Unique identifier for a given organization.
	// Required: true
	OrganizationID *string `json:"organizationId"`
}

// Validate validates this v1 get attestation document request
func (m *V1GetAttestationDocumentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnclaveType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrganizationID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetAttestationDocumentRequest) validateEnclaveType(formats strfmt.Registry) error {

	if err := validate.Required("enclaveType", "body", m.EnclaveType); err != nil {
		return err
	}

	return nil
}

func (m *V1GetAttestationDocumentRequest) validateOrganizationID(formats strfmt.Registry) error {

	if err := validate.Required("organizationId", "body", m.OrganizationID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 get attestation document request based on context it is used
func (m *V1GetAttestationDocumentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1GetAttestationDocumentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetAttestationDocumentRequest) UnmarshalBinary(b []byte) error {
	var res V1GetAttestationDocumentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
