// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1GetAttestationDocumentResponse v1 get attestation document response
//
// swagger:model v1GetAttestationDocumentResponse
type V1GetAttestationDocumentResponse struct {

	// Raw (CBOR-encoded) attestation document.
	// Required: true
	// Format: byte
	AttestationDocument *strfmt.Base64 `json:"attestationDocument"`
}

// Validate validates this v1 get attestation document response
func (m *V1GetAttestationDocumentResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttestationDocument(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetAttestationDocumentResponse) validateAttestationDocument(formats strfmt.Registry) error {

	if err := validate.Required("attestationDocument", "body", m.AttestationDocument); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 get attestation document response based on context it is used
func (m *V1GetAttestationDocumentResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1GetAttestationDocumentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetAttestationDocumentResponse) UnmarshalBinary(b []byte) error {
	var res V1GetAttestationDocumentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
