// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// NewPublicAPIServiceGetAttestationDocumentParams creates a new PublicAPIServiceGetAttestationDocumentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceGetAttestationDocumentParams() *PublicAPIServiceGetAttestationDocumentParams {
	return &PublicAPIServiceGetAttestationDocumentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceGetAttestationDocumentParamsWithTimeout creates a new PublicAPIServiceGetAttestationDocumentParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceGetAttestationDocumentParamsWithTimeout(timeout time.Duration) *PublicAPIServiceGetAttestationDocumentParams {
	return &PublicAPIServiceGetAttestationDocumentParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceGetAttestationDocumentParamsWithContext creates a new PublicAPIServiceGetAttestationDocumentParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceGetAttestationDocumentParamsWithContext(ctx context.Context) *PublicAPIServiceGetAttestationDocumentParams {
	return &PublicAPIServiceGetAttestationDocumentParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceGetAttestationDocumentParamsWithHTTPClient creates a new PublicAPIServiceGetAttestationDocumentParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceGetAttestationDocumentParamsWithHTTPClient(client *http.Client) *PublicAPIServiceGetAttestationDocumentParams {
	return &PublicAPIServiceGetAttestationDocumentParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceGetAttestationDocumentParams contains all the parameters to send to the API endpoint

	for the public Api service get attestation document operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceGetAttestationDocumentParams struct {

	// Body.
	Body *models.V1GetAttestationDocumentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service get attestation document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceGetAttestationDocumentParams) WithDefaults() *PublicAPIServiceGetAttestationDocumentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service get attestation document params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceGetAttestationDocumentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service get attestation document params
func (o *PublicAPIServiceGetAttestationDocumentParams) WithTimeout(timeout time.Duration) *PublicAPIServiceGetAttestationDocumentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service get attestation document params
func (o *PublicAPIServiceGetAttestationDocumentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service get attestation document params
func (o *PublicAPIServiceGetAttestationDocumentParams) WithContext(ctx context.Context) *PublicAPIServiceGetAttestationDocumentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service get attestation document params
func (o *PublicAPIServiceGetAttestationDocumentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service get attestation document params
func (o *PublicAPIServiceGetAttestationDocumentParams) WithHTTPClient(client *http.Client) *PublicAPIServiceGetAttestationDocumentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service get attestation document params
func (o *PublicAPIServiceGetAttestationDocumentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service get attestation document params
func (o *PublicAPIServiceGetAttestationDocumentParams) WithBody(body *models.V1GetAttestationDocumentRequest) *PublicAPIServiceGetAttestationDocumentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service get attestation document params
func (o *PublicAPIServiceGetAttestationDocumentParams) SetBody(body *models.V1GetAttestationDocumentRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceGetAttestationDocumentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
