// Code generated by go-swagger; DO NOT EDIT.

package attestation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/0xkey-io/sdk-go/pkg/api/models"
)

// PublicAPIServiceGetAttestationDocumentReader is a Reader for the PublicAPIServiceGetAttestationDocument structure.
type PublicAPIServiceGetAttestationDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicAPIServiceGetAttestationDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicAPIServiceGetAttestationDocumentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPublicAPIServiceGetAttestationDocumentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPublicAPIServiceGetAttestationDocumentOK creates a PublicAPIServiceGetAttestationDocumentOK with default headers values
func NewPublicAPIServiceGetAttestationDocumentOK() *PublicAPIServiceGetAttestationDocumentOK {
	return &PublicAPIServiceGetAttestationDocumentOK{}
}

/*
PublicAPIServiceGetAttestationDocumentOK describes a response with status code 200, with default header values.

A successful response.
*/
type PublicAPIServiceGetAttestationDocumentOK struct {
	Payload *models.V1GetAttestationDocumentResponse
}

// IsSuccess returns true when this public Api service get attestation document o k response has a 2xx status code
func (o *PublicAPIServiceGetAttestationDocumentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this public Api service get attestation document o k response has a 3xx status code
func (o *PublicAPIServiceGetAttestationDocumentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service get attestation document o k response has a 4xx status code
func (o *PublicAPIServiceGetAttestationDocumentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this public Api service get attestation document o k response has a 5xx status code
func (o *PublicAPIServiceGetAttestationDocumentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service get attestation document o k response a status code equal to that given
func (o *PublicAPIServiceGetAttestationDocumentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the public Api service get attestation document o k response
func (o *PublicAPIServiceGetAttestationDocumentOK) Code() int {
	return 200
}

func (o *PublicAPIServiceGetAttestationDocumentOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_attestation][%d] publicApiServiceGetAttestationDocumentOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceGetAttestationDocumentOK) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_attestation][%d] publicApiServiceGetAttestationDocumentOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceGetAttestationDocumentOK) GetPayload() *models.V1GetAttestationDocumentResponse {
	return o.Payload
}

func (o *PublicAPIServiceGetAttestationDocumentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetAttestationDocumentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceGetAttestationDocumentDefault creates a PublicAPIServiceGetAttestationDocumentDefault with default headers values
func NewPublicAPIServiceGetAttestationDocumentDefault(code int) *PublicAPIServiceGetAttestationDocumentDefault {
	return &PublicAPIServiceGetAttestationDocumentDefault{
		_statusCode: code,
	}
}

/*
PublicAPIServiceGetAttestationDocumentDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PublicAPIServiceGetAttestationDocumentDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this public Api service get attestation document default response has a 2xx status code
func (o *PublicAPIServiceGetAttestationDocumentDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this public Api service get attestation document default response has a 3xx status code
func (o *PublicAPIServiceGetAttestationDocumentDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this public Api service get attestation document default response has a 4xx status code
func (o *PublicAPIServiceGetAttestationDocumentDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this public Api service get attestation document default response has a 5xx status code
func (o *PublicAPIServiceGetAttestationDocumentDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this public Api service get attestation document default response a status code equal to that given
func (o *PublicAPIServiceGetAttestationDocumentDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the public Api service get attestation document default response
func (o *PublicAPIServiceGetAttestationDocumentDefault) Code() int {
	return o._statusCode
}

func (o *PublicAPIServiceGetAttestationDocumentDefault) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_attestation][%d] PublicApiService_GetAttestationDocument default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceGetAttestationDocumentDefault) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_attestation][%d] PublicApiService_GetAttestationDocument default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceGetAttestationDocumentDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PublicAPIServiceGetAttestationDocumentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
